its spaces
Signed-off-by: Andrew Klotz <agc.klotz@gmail.com>

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -31,68 +31,68 @@ tmpd() {
 
 # Get colors in manual pages
 man() {
-	env \
-		LESS_TERMCAP_mb="$(printf '\e[1;31m')" \
-		LESS_TERMCAP_md="$(printf '\e[1;31m')" \
-		LESS_TERMCAP_me="$(printf '\e[0m')" \
-		LESS_TERMCAP_se="$(printf '\e[0m')" \
-		LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
-		LESS_TERMCAP_ue="$(printf '\e[0m')" \
-		LESS_TERMCAP_us="$(printf '\e[1;32m')" \
-		man "$@"
+  env \
+    LESS_TERMCAP_mb="$(printf '\e[1;31m')" \
+    LESS_TERMCAP_md="$(printf '\e[1;31m')" \
+    LESS_TERMCAP_me="$(printf '\e[0m')" \
+    LESS_TERMCAP_se="$(printf '\e[0m')" \
+    LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
+    LESS_TERMCAP_ue="$(printf '\e[0m')" \
+    LESS_TERMCAP_us="$(printf '\e[1;32m')" \
+    man "$@"
 }
 
 # Modified version of https://github.com/zeke/ghwd
 repo() {
-	# Figure out github repo base URL
-	local base_url
-	base_url=$(git config --get remote.origin.url)
-	base_url=${base_url%\.git} # remove .git from end of string
+  # Figure out github repo base URL
+  local base_url
+  base_url=$(git config --get remote.origin.url)
+  base_url=${base_url%\.git} # remove .git from end of string
 
-	# Fix git@github.com: URLs
-	base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
+  # Fix git@github.com: URLs
+  base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
 
-	# Fix git://github.com URLS
-	base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
+  # Fix git://github.com URLS
+  base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
 
-	# Fix git@bitbucket.org: URLs
-	base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
+  # Fix git@bitbucket.org: URLs
+  base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
 
-	# Fix git@gitlab.com: URLs
-	base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
+  # Fix git@gitlab.com: URLs
+  base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
 
-	# Validate that this folder is a git folder
-	if ! git branch 2>/dev/null 1>&2 ; then
-		echo "Not a git repo!"
-		exit $?
-	fi
+  # Validate that this folder is a git folder
+  if ! git branch 2>/dev/null 1>&2 ; then
+    echo "Not a git repo!"
+    exit $?
+  fi
 
-	# Find current directory relative to .git parent
-	full_path=$(pwd)
-	git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
-	relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
+  # Find current directory relative to .git parent
+  full_path=$(pwd)
+  git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
+  relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
 
-	# If filename argument is present, append it
-	if [ "$1" ]; then
-		relative_path="$relative_path/$1"
-	fi
+  # If filename argument is present, append it
+  if [ "$1" ]; then
+    relative_path="$relative_path/$1"
+  fi
 
-	# Figure out current git branch
-	# git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
-	git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+  # Figure out current git branch
+  # git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+  git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
 
-	# Remove cruft from branchname
-	branch=${git_where#refs\/heads\/}
-	branch=${branch#remotes\/origin\/}
+  # Remove cruft from branchname
+  branch=${git_where#refs\/heads\/}
+  branch=${branch#remotes\/origin\/}
 
-	[[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
-	url="$base_url/$tree/$branch$relative_path"
+  [[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
+  url="$base_url/$tree/$branch$relative_path"
 
 
   for opener in xdg-open open cygstart "start"; do
     if command -v $opener; then
-	    echo "Calling $(type $opener) for $url"
-	    $opener "$url" &> /dev/null || (echo "Using $(type opener) to open URL failed." && exit 1);
+      echo "Calling $(type $opener) for $url"
+      $opener "$url" &> /dev/null || (echo "Using $(type opener) to open URL failed." && exit 1);
       break;
     fi
   done
@@ -103,17 +103,17 @@ repo() {
 # `less` with options to preserve color and line numbers, unless the output is
 # small enough for one screen.
 tre() {
-	tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
+  tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
 }
 
 # https://gist.github.com/willurd/5720255
 # Start an HTTP server from a directory, optionally specifying the port
 server() {
-	local port="${1:-8000}"
-	sleep 1 && open "http://localhost:${port}/" &
-	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
-	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
-	# python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nmap[".wasm"] = "application/wasm";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
+  local port="${1:-8000}"
+  sleep 1 && open "http://localhost:${port}/" &
+  # Set the default Content-Type to `text/plain` instead of `application/octet-stream`
+  # And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
+  # python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nmap[".wasm"] = "application/wasm";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
   python3 -m http.server "${port}"
 }
 
@@ -511,19 +511,19 @@ entropy() {
 ###########
 
 restart_gpgagent(){
-	# Restart the gpg agent.
-	echo "Restarting gpg-agent and scdaemon..."
-	echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
+  # Restart the gpg agent.
+  echo "Restarting gpg-agent and scdaemon..."
+  echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
 
-	echo "Killing processes..."
-	# shellcheck disable=SC2046
-	kill -9 $(pgrep scdaemon) $(pgrep gpg-agent) >/dev/null 2>&1
-	echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
+  echo "Killing processes..."
+  # shellcheck disable=SC2046
+  kill -9 $(pgrep scdaemon) $(pgrep gpg-agent) >/dev/null 2>&1
+  echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
 
-	gpgconf --reload gpg-agent
-	gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
+  gpgconf --reload gpg-agent
+  gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
 
-	echo "Restarted gpg-agent and scdaemon..."
+  echo "Restarted gpg-agent and scdaemon..."
 }
 
 # gpg_export_sgpg_export_secret_subkeyubkey agc.klotz@gmail.com 0xABC123 signing
