open repo for project

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -42,6 +42,62 @@ man() {
 		man "$@"
 }
 
+# Modified version of https://github.com/zeke/ghwd
+repo() {
+	# Figure out github repo base URL
+	local base_url
+	base_url=$(git config --get remote.origin.url)
+	base_url=${base_url%\.git} # remove .git from end of string
+
+	# Fix git@github.com: URLs
+	base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
+
+	# Fix git://github.com URLS
+	base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
+
+	# Fix git@bitbucket.org: URLs
+	base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
+
+	# Fix git@gitlab.com: URLs
+	base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
+
+	# Validate that this folder is a git folder
+	if ! git branch 2>/dev/null 1>&2 ; then
+		echo "Not a git repo!"
+		exit $?
+	fi
+
+	# Find current directory relative to .git parent
+	full_path=$(pwd)
+	git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
+	relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
+
+	# If filename argument is present, append it
+	if [ "$1" ]; then
+		relative_path="$relative_path/$1"
+	fi
+
+	# Figure out current git branch
+	# git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+	git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+
+	# Remove cruft from branchname
+	branch=${git_where#refs\/heads\/}
+	branch=${branch#remotes\/origin\/}
+
+	[[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
+	url="$base_url/$tree/$branch$relative_path"
+
+
+  for opener in xdg-open open cygstart "start"; do
+    if command -v $opener; then
+	    echo "Calling $(type $opener) for $url"
+	    $opener "$url" &> /dev/null || (echo "Using $(type opener) to open URL failed." && exit 1);
+      break;
+    fi
+  done
+}
+
 # Start an HTTP server from a directory, optionally specifying the port
 server() {
 	local port="${1:-8000}"
@@ -428,12 +484,12 @@ entropy() {
 restart_gpgagent(){
 	# Restart the gpg agent.
 	echo "Restarting gpg-agent and scdaemon..."
-	echo -e "\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
+	echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
 
 	echo "Killing processes..."
 	# shellcheck disable=SC2046
 	kill -9 $(pgrep scdaemon) $(pgrep gpg-agent) >/dev/null 2>&1
-	echo -e "\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
+	echo -e "\\tgpg-agent: $(pgrep gpg-agent) | scdaemon: $(pgrep scdaemon)"
 
 	gpgconf --reload gpg-agent
 	gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
